name: Daniel Eden
description: Designer
url: http://daneden.me

markdown: rdiscount
rdiscount:
  extensions:
    - smart

pygments: true

permalink: pretty

include: [".htaccess"]
exclude: ["node_modules", "package.json", "config.rb", "Gruntfile.js"]